# Generated by Django 5.1.5 on 2025-01-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='api_key',
            new_name='aws_access_key',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='secret_key',
            new_name='aws_secret_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='azure_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='azure_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='azure_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='azure_tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gcp_key_file',
            field=models.FileField(blank=True, null=True, upload_to='gcp_keys/'),
        ),
    ]
