# Generated by Django 5.1.5 on 2025-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile_git_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='git_private_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='git_repository',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aws_access_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aws_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='azure_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='azure_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='azure_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='azure_tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cloud_provider',
            field=models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('azure', 'Azure')], default='aws', max_length=10),
        ),
    ]
