# Generated by Django 5.1.5 on 2025-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_gitrepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitrepository',
            name='repo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
