# Generated by Django 5.1.5 on 2025-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_gitrepository_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва сервісу'),
        ),
    ]
