# Generated by Django 5.1.5 on 2025-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_gitrepository_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='branch',
            field=models.CharField(default='main', max_length=100, verbose_name='Git Branch'),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='docker_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Docker Image URI'),
        ),
    ]
